#!/bin/bash
nvm use default &> /dev/null && nvm alias default stable &> /dev/null

export RBENV_ROOT="${HOME}/.rbenv

if [[ -d $RBENV_ROOT ]]; then
    export PATH="${RBENV_ROOT}/bin:${PATH}"
    eval "$(rbenv init -)"
fi
export PATH="./bin:${PATH}"

