#!/bin/bash
set -ex

ruby --version | grep 2\..\..

rails -v

for rubyversion in 1.9.3 2.1.5 2.2.4 2.3.0; do
	set +x;
	echo "+ rvm use $rubyversion"
	rvm use $rubyversion
	echo "+ ruby --version | grep $rubyversion"
	ruby --version | grep $rubyversion
	rails -v
	echo "+ puts "hello" | ruby"
	echo 'puts "hello"' | ruby
	set -x
done

