FROM cloud9/workspace

# first attempt by Jeremy Ellis to add the Android_SDK

MAINTAINER Fabian Jakobs <fabian@c9.io>

ADD ./files/workspace /home/ubuntu/workspace

RUN chmod -R g+w /home/ubuntu/workspace && \
    chown -R ubuntu:ubuntu /home/ubuntu/workspace
    
    
    
    
    
    
